services:
  # SvelteKit Frontend
  client:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    container_name: trackly-client-only
    environment:
      - NODE_ENV=production
      - PORT=5173
      - HOST=0.0.0.0
      # Connect to external backend (assuming it's running on host)
      - PUBLIC_API_BASE_URL=http://localhost:8000/api
      - VITE_API_BASE_URL=http://localhost:8000/api
    ports:
      - "5173:5173"
    restart: unless-stopped
    networks:
      - trackly-client-network
    
networks:
  trackly-client-network:
    driver: bridge